In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame
import matplotlib.pyplot as plt

In [2]:
a = 5.0
isinstance(a, float) 
#isinstance() isused to verify datatype of variable

True

In [3]:
def array_zeros():
    zeros_array = np.zeros((3,4,2))
    return zeros_array


def array_reshaped_zeros():
    zeros_array = array_zeros()
    zeros_array_reshaped = zeros_array.reshape((2,3,4))
    return zeros_array_reshaped

print array_reshaped_zeros()

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [4]:
import numpy as np

In [5]:
path = "/home/sejal/Documents/datascience/assignments/data/ipl_matches_small.csv"
ipl_matches_array =np.genfromtxt(path, dtype="|S50", skip_header=1, delimiter=",")

In [6]:
def get_total_deliveries_played(batsman):
	batsman_col = ipl_matches_array[:,13]
	return len(batsman_col[batsman_col == batsman])


get_total_deliveries_played("SR Tendulkar")

84

In [7]:
def get_wicket_delivery_numbers_array(player):
    played_out = ipl_matches_array[:,[11,20]]
    return played_out[played_out[:,1] == player][:,0]
    
get_wicket_delivery_numbers_array("ST Jayasuriya")

array(['3.2', '14.4', '1.4'], dtype='|S50')

In [8]:
def get_toss_win_count(team):
    toss_winner = ipl_matches_array[:,[0,5]]    
    return len(np.unique(toss_winner[toss_winner[:,1] == team][:,0]))
    
get_toss_win_count("Mumbai Indians")

2

In [9]:

def get_all_sixes_filter():
    return ipl_matches_array[:,16].astype(np.int16) == 6

get_all_sixes_filter()

array([False, False, False, ..., False, False, False])

In [10]:
def create_delivery_series():
    return pd.Series(ipl_matches_array[:,11])
print create_delivery_series()

0        0.1
1        0.2
2        0.3
3        0.4
4        0.5
5        0.6
6        0.7
7        0.8
8        1.1
9        1.2
10       1.3
11       1.4
12       1.5
13       1.6
14       2.1
15       2.2
16       2.3
17       2.4
18       2.5
19       2.6
20       3.1
21       3.2
22       3.3
23       3.4
24       3.5
25       3.6
26       3.7
27       4.1
28       4.2
29       4.3
        ... 
1421    13.4
1422    13.5
1423    13.6
1424    13.7
1425    14.1
1426    14.2
1427    14.3
1428    14.4
1429    14.5
1430    14.6
1431    15.1
1432    15.2
1433    15.3
1434    15.4
1435    15.5
1436    15.6
1437    16.1
1438    16.2
1439    16.3
1440    16.4
1441    16.5
1442    16.6
1443    17.1
1444    17.2
1445    17.3
1446    17.4
1447    17.5
1448    17.6
1449    17.7
1450    18.1
Length: 1451, dtype: object


In [11]:
def create_runs_series(match_code):
    match_data = ipl_matches_array[ ipl_matches_array[:,0] == match_code]
    pd_series = pd.Series(match_data[:,16], index=match_data[:,11])
    return pd_series
    
print type(create_runs_series("392203"))

<class 'pandas.core.series.Series'>


In [12]:
path = "/home/sejal/Documents/datascience/assignments/data/ipl_dataset.csv"
def read_csv_data_to_df(path):
    df = pd.read_csv(path)
    return df
df = read_csv_data_to_df(path)


In [13]:
ipl_df = read_csv_data_to_df(path)

#Solution
def get_unique_venues():
    return np.unique(ipl_df['venue'])
get_unique_venues()

array(['Barabati Stadium', 'Brabourne Stadium', 'Buffalo Park',
       'De Beers Diamond Oval', 'Dr DY Patil Sports Academy',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
       'Dubai International Cricket Stadium', 'Eden Gardens',
       'Feroz Shah Kotla', 'Green Park',
       'Himachal Pradesh Cricket Association Stadium',
       'Holkar Cricket Stadium', 'JSCA International Stadium Complex',
       'Kingsmead', 'M Chinnaswamy Stadium',
       'MA Chidambaram Stadium, Chepauk',
       'Maharashtra Cricket Association Stadium', 'Nehru Stadium',
       'New Wanderers Stadium', 'Newlands', 'OUTsurance Oval',
       'Punjab Cricket Association IS Bindra Stadium, Mohali',
       'Punjab Cricket Association Stadium, Mohali',
       'Rajiv Gandhi International Stadium, Uppal',
       'Sardar Patel Stadium, Motera',
       'Saurashtra Cricket Association Stadium', 'Sawai Mansingh Stadium',
       'Shaheed Veer Narayan Singh International Stadium',
       'Sharjah Cricket S

In [14]:
def get_run_counts():
    return ipl_df["runs"].value_counts()
    
print get_run_counts()

0    55870
1    50087
4    15409
2     8835
6     5806
3      473
5       42
Name: runs, dtype: int64


In [15]:
def get_match_specific_df(match_code):
    return  ipl_df[ipl_df["match_code"] == match_code]
get_match_specific_df(392203)

match_code        date         city         venue                  team1  \
0        392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
1        392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
2        392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
3        392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
4        392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
5        392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
6        392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
7        392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
8        392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
9        392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
10       392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
11       392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
12       392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
13       392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
14       392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
15       392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
16       392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
17       392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
18       392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
19       392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
20       392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
21       392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
22       392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
23       392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
24       392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
25       392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
26       392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
27       392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
28       392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
29       392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
..          ...         ...          ...           ...                    ...   
223      392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
224      392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
225      392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
226      392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
227      392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
228      392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
229      392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
230      392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
231      392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
232      392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
233      392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
234      392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
235      392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
236      392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
237      392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
238      392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
239      392203  2009-05-01  East London  Buffalo Park  Kolkata Knight Riders   
240      392203  2009-05-01  East Lo

In [16]:
def create_bowler_filter(bowler):
    bowler_sr = ipl_df["bowler"]
    return bowler_sr == bowler
create_bowler_filter("I Sharma")

0          True
1          True
2          True
3          True
4          True
5          True
6          True
7          True
8         False
9         False
10        False
11        False
12        False
13        False
14         True
15         True
16         True
17         True
18         True
19         True
20        False
21        False
22        False
23        False
24        False
25        False
26        False
27        False
28        False
29        False
          ...  
136492    False
136493    False
136494    False
136495    False
136496    False
136497    False
136498    False
136499    False
136500    False
136501    False
136502    False
136503    False
136504    False
136505    False
136506    False
136507    False
136508    False
136509    False
136510    False
136511    False
136512    False
136513    False
136514    False
136515    False
136516    False
136517    False
136518    False
136519    False
136520    False
136521    False
Name: bowler, Length: 13

In [17]:
ipl_df = read_csv_data_to_df(path)
def get_match_innings_runs():
    return ipl_df.groupby(["match_code","inning"])[["runs"]].sum()
get_match_innings_runs()

runs
match_code inning      
335982     1        205
           2         63
335983     1        234
           2        196
335984     1        122
           2        122
335985     1        154
           2        161
335986     1        100
           2         84
335987     1        162
           2        156
335988     1        137
           2        131
335989     1        190
           2        189
335990     1        208
           2        210
335991     1        175
           2        109
335992     1        129
           2        135
335993     1        139
           2        134
335994     1        143
           2        146
335995     1        147
           2        153
335996     1        174
           2        158
...                 ...
980991     1        176
           2        171
980993     1        199
           2        123
980995     1        171
           2        183
980997     1        119
           2         69
980999     1        203
           2        114
981001     1        117
           2        108
981003     1        155
           2        147
981005     1        168
           2        165
981007     1        164
           2        167
981009     1        167
           2        138
981011     1        132
           2        129
981013     1        147
           2        143
981015     1        156
           2        131
981017     1        157
           2        161
981019     1        194
           2        191

[1152 rows x 1 columns]

In [18]:
def get_runs_counts_by_match():
    pddf = pd.pivot_table(ipl_df,index=ipl_df["match_code"],columns=ipl_df["runs"],values = "runs",aggfunc="count")
    print pddf.columns
print get_runs_counts_by_match()

Int64Index([0, 1, 2, 3, 4, 5, 6], dtype='int64', name=u'runs')
None
