In [130]:
pcm = [
    [67,99,100],
    [99,100,76],
    [90,90,100]    
]

In [131]:
import numpy as np


n1 = np.array(pcm, dtype=np.float16)
print n1
print type(n1)
print n1.ndim
print n1.shape
print n1.dtype

[[  67.   99.  100.]
 [  99.  100.   76.]
 [  90.   90.  100.]]
<type 'numpy.ndarray'>
2
(3, 3)
float16


In [132]:
#indexing
print n1[0]
print n1[0][1] # Dont' do the way it is done in 2-D list
print n1[0,1] # Always, USE numpy way to get index

print n1[2, 0] # get physics marks for third student
print n1[-1,1] # get chemistry marks of last student
print n1[0, -1]
print n1[[0, -1]] # get all marks of first and last students

print n1[[0, -1],1]

print n1[[-2, -1], 2]
print n1[-2:, -1]


[  67.   99.  100.]
99.0
99.0
90.0
90.0
100.0
[[  67.   99.  100.]
 [  90.   90.  100.]]
[ 99.  90.]
[  76.  100.]
[  76.  100.]


In [133]:
#Slicing
print n1

print n1[-2:]
print n1[-2:,1:] # get chemistry and maths marks for last two students

# marks scored in phy and chem for 1st tow students
print n1 [:2,:2]
print n1[0:, -2:]
print n1[0:,-1:]

[[  67.   99.  100.]
 [  99.  100.   76.]
 [  90.   90.  100.]]
[[  99.  100.   76.]
 [  90.   90.  100.]]
[[ 100.   76.]
 [  90.  100.]]
[[  67.   99.]
 [  99.  100.]]
[[  99.  100.]
 [ 100.   76.]
 [  90.  100.]]
[[ 100.]
 [  76.]
 [ 100.]]


In [134]:
# marks scored in chem and math first ans last stud
print n1
print n1[[0, -1],1:]


[[  67.   99.  100.]
 [  99.  100.   76.]
 [  90.   90.  100.]]
[[  99.  100.]
 [  90.  100.]]


In [135]:
# aggregations

print n1
mean_marks = n1.mean(axis=0)
print mean_marks # mean marks for PCM across all students
print n1.sum(axis=1) # total marks of all subjects for each students wise

#get standeviation of the P and M marks of last two students of class

physics_n_maths = n1[-2:,[0,2]]

print physics_n_maths

std_physics_n_maths = np.std(physics_n_maths, axis=0)
print std_physics_n_maths

#physics_n_maths = n1[-2:,0]

#print physics_n_maths




[[  67.   99.  100.]
 [  99.  100.   76.]
 [  90.   90.  100.]]
[ 85.3125  96.3125  92.    ]
[ 266.  275.  280.]
[[  99.   76.]
 [  90.  100.]]
[  4.5  12. ]


0 is Y axis 1 is X axis

In [138]:
print n1
# get chem + maths marks for first and last student

n2 = n1[[0,-1], 1:]
print n2
sum = n2.sum(axis=1)
print sum

n2 = n1[[0,-1], -2:]
print n2


[[  67.   99.  100.]
 [  99.  100.   76.]
 [  90.   90.  100.]]
[[  99.  100.]
 [  90.  100.]]
[ 199.  190.]
[[  99.  100.]
 [  90.  100.]]


In [127]:
# reduce extra marks from P for all students
print n1

n1[:,0] -= 1

[[  67.   99.  100.]
 [  99.  100.   76.]
 [  90.   90.  100.]]


In [128]:
# make all 100 marks in M as 0 as they copied
print n1

# create maths into seperate variable
maths =  n1[:,-1]
#changing nything to maths will change in n1 aswell
maths[maths == 100] = 0

print n1

[[  66.   99.  100.]
 [  98.  100.   76.]
 [  89.   90.  100.]]
[[  66.   99.    0.]
 [  98.  100.   76.]
 [  89.   90.    0.]]


In [129]:
# all studs above = 90 all students make weight 1 else weight 0
print n1

np.where(n1 >= 90, 1,0)


[[  66.   99.    0.]
 [  98.  100.   76.]
 [  89.   90.    0.]]


array([[0, 1, 0],
       [1, 1, 0],
       [0, 1, 0]])