In [127]:

marks = (7,8,9,9,2,1,1,6,4,5,4)

In [3]:
import numpy as np

In [129]:
#ID numpy array
n1 = np.array(marks)
print n1
print type(n1)
print n1.ndim  # one dimension
print n1.shape # is a tuple
print n1.dtype #data type

[7 8 9 9 2 1 1 6 4 5 4]
<type 'numpy.ndarray'>
1
(11,)
int64


In [130]:
#ID numpy array
n1 = np.array(marks, dtype =np.int8) #adds data type as int16
print n1
print type(n1)
print n1[[0,2]]
print n1.ndim  # one dimension
print n1.shape # is a tuple
print n1.dtype #data type

[7 8 9 9 2 1 1 6 4 5 4]
<type 'numpy.ndarray'>
[7 9]
1
(11,)
int8


In [131]:
# vectorized computation
corrected_marks = n1 + 1 # Easily add 1 to all elements of array
print corrected_marks
print type(corrected_marks)


sq = n1 ** 2
print sq
print sq / 2
print sq % 2

[ 8  9 10 10  3  2  2  7  5  6  5]
<type 'numpy.ndarray'>
[49 64 81 81  4  1  1 36 16 25 16]
[24 32 40 40  2  0  0 18  8 12  8]
[1 0 1 1 0 1 1 0 0 1 0]


In [132]:
# Indexing
print n1
print n1[0]
print n1[1]
print n1[-1]


print n1[[0,2,5]]
print n1[[5,4, -1, -5]] # return data from multiple indexes
na = n1 [[0, -1, -2]]
print type(na)
print na


[7 8 9 9 2 1 1 6 4 5 4]
7
8
4
[7 9 1]
[1 2 4 1]
<type 'numpy.ndarray'>
[7 4 5]


In [133]:
# Slicing
print n1
first_three = n1[:3]
print first_three
print type(first_three)

print n1[-3 :]

[7 8 9 9 2 1 1 6 4 5 4]
[7 8 9]
<type 'numpy.ndarray'>
[4 5 4]


In [134]:
# Filtering
print n1

# marks greater than 5
greater_than_5 = n1 > 5
print greater_than_5

greater_than_5 = n1[n1 > 5]
print greater_than_5


[7 8 9 9 2 1 1 6 4 5 4]
[ True  True  True  True False False False  True False False False]
[7 8 9 9 6]


In [135]:
evens = n1[(n1 % 2 == 0) | (n1 > 5)] # get evens OR no > 5
print evens

[7 8 9 9 2 6 4 4]


In [136]:
n2 = [10, 4, 5, 6, 2, 2, 3, 10, 10]
n2 = np.array(n2 , dtype = np.int16)

print n2
print type(n2)
#multiple indexing + assignment
n2[[0, -1 ,-2]] = 9 # DO -1 from all 10's

n2[[0, -1 ,-2]] = 10

#filtering + assignment
n2[n2 == 10] = 9 
print n2


[10  4  5  6  2  2  3 10 10]
<type 'numpy.ndarray'>
[9 4 5 6 2 2 3 9 9]


In [137]:
print n1

n3 = np.where(n1 >= 5, 1, 0)
print n3

n4 = np.where(n1 >=5 , 'abc', 'dumb')
print n4

[7 8 9 9 2 1 1 6 4 5 4]
[1 1 1 1 0 0 0 1 0 1 0]
['abc' 'abc' 'abc' 'abc' 'dumb' 'dumb' 'dumb' 'abc' 'dumb' 'abc' 'dumb']


In [138]:
# Aggregations 

print n1
print n1.sum()
print n1.mean() # mean
print n1.max()
print n1.min()
print np.median(n1) # median
print np.std(n1) # standard deviation
print np.var(n1) # varirance


[7 8 9 9 2 1 1 6 4 5 4]
56
5.09090909091
9
1
5.0
2.84299923111
8.0826446281


In [139]:
print n1
print n1.cumsum()
uu = np.unique(n1) # get unique
print uu
print type(uu) 



# count how many times marks is repeated
marks_count = np.unique(n1, return_counts=True)
print marks_count
print type(marks_count)
print marks_count[0]

# print elemets with its respective occurence counts
element , counts = marks_count
i = 0
while i < len(element):
    print element[i], ' : ', counts[i]
    i = i + 1

[7 8 9 9 2 1 1 6 4 5 4]
[ 7 15 24 33 35 36 37 43 47 52 56]
[1 2 4 5 6 7 8 9]
<type 'numpy.ndarray'>
(array([1, 2, 4, 5, 6, 7, 8, 9], dtype=int8), array([2, 1, 2, 1, 1, 1, 1, 2]))
<type 'tuple'>
[1 2 4 5 6 7 8 9]
1  :  2
2  :  1
4  :  2
5  :  1
6  :  1
7  :  1
8  :  1
9  :  2


In [140]:
marks_freq = zip(element, counts)
print marks_freq



for element in marks_freq:
    print element[0], ' : ', element[1]

[(1, 2), (2, 1), (4, 2), (5, 1), (6, 1), (7, 1), (8, 1), (9, 2)]
1  :  2
2  :  1
4  :  2
5  :  1
6  :  1
7  :  1
8  :  1
9  :  2


In [141]:
print n1

[7 8 9 9 2 1 1 6 4 5 4]


In [142]:
print n1[(n1 % 3 == 0) & (n1 > 6)]
print n1[(n1 % 2 == 0) | (n1 > 7)]

[9 9]
[8 9 9 2 6 4 4]


In [143]:
n1[n1 > 4] = 9
print n1

[9 9 9 9 2 1 1 9 4 9 4]


In [5]:
a = np.array([-20,-15,0,15,20], dtype =np.int16) #adds data type as int16
print a.std()

15.811388300841896


In [16]:
x = 10+40+200+2500+200
#print x
#print x/68

tmp = 10 +15+ 18+ 19+ 23+ 24+ 28+ 26
print tmp /8
print tmp


z1 = np.array([10,15, 18, 19, 23, 24, 28,26])

print z1

20
163
