In [17]:
import numpy as np
import numpy.random as rd

In [18]:
n1 =  np.arange(10)
print n1
print type(n1)

print np.arange(5,21)

[0 1 2 3 4 5 6 7 8 9]
<type 'numpy.ndarray'>
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [19]:
print np.zeros(6)
print np.ones(10)

[ 0.  0.  0.  0.  0.  0.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


In [38]:
im = np.identity(4)
print im
ins = np.identity(4,dtype = np.int16)
print ins


[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [21]:
n2 = np.arange(10).reshape(5,2) # make one-D to 3,3 Dimension
print n2

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [22]:
n2.ravel() #make multi-D to one-D

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
print n2
n3 = n2.T
print n3

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 2 4 6 8]
 [1 3 5 7 9]]


In [39]:
rd.randn(3,4)
rd.randn(4)

array([ 0.30931206, -0.63202182, -1.23868294,  0.44770806])

In [46]:
rd.normal(size=(3,3))
rd.normal(size=(3,))

array([-0.58909765, -0.56583601, -1.81380129])