In [33]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression # Logistic Regression module import
from sklearn.ensemble import RandomForestRegressor
from sklearn import metrics

In [2]:
df = pd.read_csv("/Users/Ramesh/Documents/DataScience/python/jupyterworkspace/ML/loan_prediction.csv")
df.head()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         0.0             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History  Loan_Status  
0             1.0            1  
1             1.0            0  
2             1.0            1  
3             1.0            1  
4             1.0            1

In [3]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=9)
print X_train.shape, y_train.shape
print X_test.shape, y_test.shape

(552, 5) (552,)
(62, 5) (62,)


In [6]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(X_train, y_train, test_size=0.1, random_state=9)
print X_train1.shape, y_train1.shape
print X_test1.shape, y_test1.shape

(496, 5) (496,)
(56, 5) (56,)


In [9]:
#Model-1
clf_gini = DecisionTreeClassifier(criterion='gini', max_depth=2)
clf_gini.fit(X_train1,y_train1)

y_prediction_gini = clf_gini.predict_proba(X_test1)[:,1]
y_prediction_gini

array([ 0.33018868,  0.33018868,  0.7890625 ,  0.7890625 ,  0.7890625 ,
        0.7890625 ,  0.7890625 ,  0.7890625 ,  0.7890625 ,  0.33018868,
        0.33018868,  0.7890625 ,  0.7890625 ,  0.7890625 ,  0.7890625 ,
        0.7890625 ,  0.7890625 ,  0.7890625 ,  0.7890625 ,  0.7890625 ,
        0.7890625 ,  0.7890625 ,  0.33018868,  0.7890625 ,  0.7890625 ,
        0.33018868,  0.7890625 ,  0.7890625 ,  0.33018868,  0.7890625 ,
        0.7890625 ,  0.7890625 ,  0.7890625 ,  0.7890625 ,  0.33018868,
        0.7890625 ,  0.7890625 ,  0.7890625 ,  0.7890625 ,  0.33018868,
        0.33018868,  0.7890625 ,  0.33018868,  0.7890625 ,  0.33018868,
        0.7890625 ,  0.33018868,  0.7890625 ,  0.7890625 ,  0.33018868,
        0.7890625 ,  0.7890625 ,  0.7890625 ,  0.7890625 ,  0.33018868,
        0.7890625 ])

In [11]:
#Model-2
clf_entropy = DecisionTreeClassifier(criterion='entropy', max_depth=9)
clf_entropy.fit(X_train1,y_train1)

y_prediction_entropy = clf_entropy.predict_proba(X_test1)[:,1]
y_prediction_entropy

array([ 0.35849057,  0.35849057,  0.92682927,  0.67857143,  1.        ,
        0.88888889,  1.        ,  1.        ,  0.67857143,  0.35849057,
        0.35849057,  0.92682927,  1.        ,  1.        ,  0.45454545,
        1.        ,  1.        ,  1.        ,  1.        ,  0.95238095,
        1.        ,  0.6       ,  1.        ,  1.        ,  0.92682927,
        0.35849057,  0.76744186,  0.        ,  0.14285714,  0.6       ,
        0.88888889,  0.4       ,  1.        ,  1.        ,  1.        ,
        0.67857143,  0.95238095,  0.6       ,  0.        ,  0.35849057,
        1.        ,  1.        ,  0.14285714,  0.76744186,  0.        ,
        1.        ,  0.14285714,  0.76744186,  1.        ,  0.35849057,
        1.        ,  0.5       ,  0.76744186,  1.        ,  1.        ,  0.        ])

In [17]:
#Model-3
clf_LR = LogisticRegression()
clf_LR.fit(X_train1, y_train1)

y_predict_LR = clf_LR.predict_proba(X_test1)[:,1]
y_predict_LR

array([ 0.35791714,  0.38540814,  0.78143552,  0.78587786,  0.76906856,
        0.78721955,  0.77422243,  0.78066258,  0.75970475,  0.37713259,
        0.3667054 ,  0.75147311,  0.75855411,  0.78453696,  0.77397198,
        0.76071281,  0.77832401,  0.7826372 ,  0.77012267,  0.77714084,
        0.77241844,  0.75246357,  0.36021222,  0.7790081 ,  0.78714171,
        0.38452508,  0.79709963,  0.77430136,  0.36536413,  0.76733824,
        0.78476001,  0.78469388,  0.77324406,  0.76196803,  0.37718705,
        0.78713743,  0.74698963,  0.81711879,  0.7853364 ,  0.38086337,
        0.37930286,  0.78248697,  0.38457594,  0.79154687,  0.41798915,
        0.77265238,  0.37578353,  0.80831882,  0.81172227,  0.38676241,
        0.78600241,  0.77946433,  0.82249444,  0.78943627,  0.35014813,
        0.77131125])

In [18]:
#Model-4
clf_LR_L1 = LogisticRegression(penalty="l1")
clf_LR_L1.fit(X_train1, y_train1)

y_predict_LR_L1 = clf_LR_L1.predict_proba(X_test1)[:,1]
y_predict_LR_L1

array([ 0.35066197,  0.37869116,  0.78328517,  0.7885229 ,  0.76917539,
        0.7887654 ,  0.77526593,  0.78389274,  0.76027282,  0.37145449,
        0.35969194,  0.75082252,  0.76232086,  0.80090642,  0.77353459,
        0.75928866,  0.78098612,  0.78499941,  0.77116399,  0.78039452,
        0.77500154,  0.75399112,  0.35482016,  0.78168165,  0.78929697,
        0.401868  ,  0.79716036,  0.77539353,  0.35973344,  0.7689074 ,
        0.78591821,  0.78795473,  0.77356051,  0.76234003,  0.3950947 ,
        0.78964057,  0.74781139,  0.8476163 ,  0.80358572,  0.37129434,
        0.37416119,  0.78415988,  0.37937439,  0.79207393,  0.46203301,
        0.77216173,  0.3701487 ,  0.80522778,  0.81282798,  0.38093619,
        0.78933067,  0.78193365,  0.81947631,  0.79217329,  0.3296444 ,
        0.77266956])

In [22]:
#Model-4
clf_LR_L2 = LogisticRegression(penalty="l1", random_state=5)
clf_LR_L2.fit(X_train1, y_train1)

y_predict_LR_L2 = clf_LR_L2.predict_proba(X_test1)[:,1]
y_predict_LR_L2

array([ 0.34956564,  0.37743508,  0.78345399,  0.78852875,  0.76978722,
        0.78907735,  0.77573557,  0.7837463 ,  0.76078165,  0.36997605,
        0.35855756,  0.75137879,  0.76196182,  0.7988165 ,  0.77437905,
        0.76037896,  0.78100955,  0.78508822,  0.77160288,  0.78019388,
        0.77506596,  0.75424886,  0.35323384,  0.78169367,  0.78942986,
        0.3964801 ,  0.79787701,  0.7758209 ,  0.35821583,  0.76920306,
        0.78627738,  0.78780371,  0.7741305 ,  0.76293637,  0.38952122,
        0.78968911,  0.74797468,  0.84319397,  0.80097691,  0.37084503,
        0.37248621,  0.78446694,  0.37774469,  0.7926313 ,  0.45201256,
        0.77304562,  0.36857388,  0.8067754 ,  0.81336549,  0.37947151,
        0.78917203,  0.78198363,  0.82108441,  0.79218017,  0.33063134,
        0.77302103])

In [32]:
all_probs = pd.DataFrame(list(zip(y_prediction_gini, y_prediction_entropy, y_predict_LR, y_predict_LR_L1, y_predict_LR_L2)), columns=['p1','p2','p3','p4','p5'])
all_probs

p1        p2        p3        p4        p5
0   0.330189  0.358491  0.357917  0.350662  0.349566
1   0.330189  0.358491  0.385408  0.378691  0.377435
2   0.789062  0.926829  0.781436  0.783285  0.783454
3   0.789062  0.678571  0.785878  0.788523  0.788529
4   0.789062  1.000000  0.769069  0.769175  0.769787
5   0.789062  0.888889  0.787220  0.788765  0.789077
6   0.789062  1.000000  0.774222  0.775266  0.775736
7   0.789062  1.000000  0.780663  0.783893  0.783746
8   0.789062  0.678571  0.759705  0.760273  0.760782
9   0.330189  0.358491  0.377133  0.371454  0.369976
10  0.330189  0.358491  0.366705  0.359692  0.358558
11  0.789062  0.926829  0.751473  0.750823  0.751379
12  0.789062  1.000000  0.758554  0.762321  0.761962
13  0.789062  1.000000  0.784537  0.800906  0.798817
14  0.789062  0.454545  0.773972  0.773535  0.774379
15  0.789062  1.000000  0.760713  0.759289  0.760379
16  0.789062  1.000000  0.778324  0.780986  0.781010
17  0.789062  1.000000  0.782637  0.784999  0.785088
18  0.789062  1.000000  0.770123  0.771164  0.771603
19  0.789062  0.952381  0.777141  0.780395  0.780194
20  0.789062  1.000000  0.772418  0.775002  0.775066
21  0.789062  0.600000  0.752464  0.753991  0.754249
22  0.330189  1.000000  0.360212  0.354820  0.353234
23  0.789062  1.000000  0.779008  0.781682  0.781694
24  0.789062  0.926829  0.787142  0.789297  0.789430
25  0.330189  0.358491  0.384525  0.401868  0.396480
26  0.789062  0.767442  0.797100  0.797160  0.797877
27  0.789062  0.000000  0.774301  0.775394  0.775821
28  0.330189  0.142857  0.365364  0.359733  0.358216
29  0.789062  0.600000  0.767338  0.768907  0.769203
30  0.789062  0.888889  0.784760  0.785918  0.786277
31  0.789062  0.400000  0.784694  0.787955  0.787804
32  0.789062  1.000000  0.773244  0.773561  0.774130
33  0.789062  1.000000  0.761968  0.762340  0.762936
34  0.330189  1.000000  0.377187  0.395095  0.389521
35  0.789062  0.678571  0.787137  0.789641  0.789689
36  0.789062  0.952381  0.746990  0.747811  0.747975
37  0.789062  0.600000  0.817119  0.847616  0.843194
38  0.789062  0.000000  0.785336  0.803586  0.800977
39  0.330189  0.358491  0.380863  0.371294  0.370845
40  0.330189  1.000000  0.379303  0.374161  0.372486
41  0.789062  1.000000  0.782487  0.784160  0.784467
42  0.330189  0.142857  0.384576  0.379374  0.377745
43  0.789062  0.767442  0.791547  0.792074  0.792631
44  0.330189  0.000000  0.417989  0.462033  0.452013
45  0.789062  1.000000  0.772652  0.772162  0.773046
46  0.330189  0.142857  0.375784  0.370149  0.368574
47  0.789062  0.767442  0.808319  0.805228  0.806775
48  0.789062  1.000000  0.811722  0.812828  0.813365
49  0.330189  0.358491  0.386762  0.380936  0.379472
50  0.789062  1.000000  0.786002  0.789331  0.789172
51  0.789062  0.500000  0.779464  0.781934  0.781984
52  0.789062  0.767442  0.822494  0.819476  0.821084
53  0.789062  1.000000  0.789436  0.792173  0.792180
54  0.330189  1.000000  0.350148  0.329644  0.330631
55  0.789062  0.000000  0.771311  0.772670  0.773021

In [34]:
rf = RandomForestRegressor(n_estimators= 1000, random_state=9)

In [37]:
rf.fit(all_probs, y_test1)
meta_prob = rf.predict(X_test1)
print meta_prob

[ 0.629  0.573  0.964  0.964  1.     1.     1.     1.     1.     0.629
  0.629  0.964  0.73   1.     1.     1.     1.     1.     1.     0.964  1.
  1.     0.629  1.     0.964  0.629  1.     1.     0.629  1.     0.964
  0.964  1.     1.     0.629  0.964  0.964  0.526  0.964  0.629  0.573  1.
  0.573  0.964  0.453  1.     0.573  0.964  0.964  0.573  0.964  1.     0.964
  0.964  0.629  1.   ]


In [39]:
auc = metrics.roc_auc_score(y_test1, meta_prob)
auc

0.83495934959349594